version: 0.0
os: linux
files:
  # - source: target/*.jar
  #   destination: /home/ubuntu/app/app.jar
  # - source: scripts/
  #   destination: /home/ubuntu/
    #destination: /home/ubuntu/scripts/ 

  - source: ./target/*.jar
    destination: /home/ubuntu/app.jar
  - source: ./scripts/
    destination: /home/ubuntu/ignite-java-asg/scripts/

  # - source: ./
  #   destination: /home/ec2-user/ignite-java-asg
 
hooks:
  BeforeInstall:
    - location: scripts/setup.sh
      runas: root
      timeout: 300
 
  AfterInstall:
    - location: scripts/run_jar.sh
      runas: root
      timeout: 300
