version: 0.0
os: linux
files:
  - source: Employee-Management-System-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/employee-management-system

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
