version: 0.0
os: linux
files:
  - source: /app.jar
    destination: /home/ec2-user/app.jar
    overwrite: true
file_exists_behavior: OVERWRITE
branch_config:
    main:
        deploymentGroupName: ignite-DG
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::920726643262:role/ignite-code-deploy-role

