version: 0.0
os: linux
files:
  - source: target/*.jar
    destination: /home/ubuntu/app/app.jar
  - source: scripts/
    destination: /home/ubuntu/scripts/
    #destination: /home/ubuntu/scripts/ 
 
hooks:
  BeforeInstall:
    - location: /home/ubuntu/scripts/setup.sh
      timeout: 300
 
  AfterInstall:
    - location: /home/ubuntu/scripts/run_jar.sh
      timeout: 300
