version: 0.0
os: linux

files:
   - source: s3://ignite-jar-bucket/my-app.zip 
     destination: /home/ubuntu/

   - source: /scripts/
     destination: /home/ubuntu/

   - source: /appspec.yml
     destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
