version: 0.0
os: linux

files:
  - source: build/Employee-Management-System-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/

  - source: scripts/
    destination: /home/ubuntu/

  - source: appspec.yml
    destination: /home/ubuntu/

permissions:
  - object: /home/ubuntu/Employee-Management-System-0.0.1-SNAPSHOT.jar
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/configure_application.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root


