name: Java CI/CD with Maven and CodeDeploy

on:
  push:
    branches:
      - feature/codedeploy

permissions:
  id-token: write
  contents: read

jobs:
  # CI Job
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run unit tests
        run: mvn test

      - name: Generate code-coverage report
        run: mvn jacoco:report

      - name: Upload code-coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

      - name: Build project and package jar
        run: mvn package -Dmaven.test.skip

      - name: List files in target directory
        run: ls -al target

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: target/*.jar

  # CD Job
  deploy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: application-jar
          path: ./target

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install required dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk

      - name: Deploy using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name "ignite-app" \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name "ignite-DG" \
            --description "Deployment from GitHub Actions" \
            --github-location repository=Khushbo08/ignite-java-asg,commitId=${GITHUB_SHA}
            --bundle-type jar \
            --file-exists-behavior OVERWRITE \
            --artifact-store ./target/*.jar
