name: Java CI/CD with Maven and CodeDeploy (S3)

on:
  push:
    branches:
      - feature/jar-s3-oidc

permissions:
  id-token: write
  contents: read

jobs:
  # CI Job
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ARN }}
          role-session-name: samplerolesession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run unit tests
        run: mvn test

      - name: Generate code-coverage report
        run: mvn jacoco:report

      - name: Upload code-coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

      - name: Build project and package jar
        run: mvn package -Dmaven.test.skip

      - name: Create deployment package
        run: |
          zip -r my-app.zip appspec.yml scripts/ target/Employee-Management-System-0.0.1-SNAPSHOT.jar

      - name: List contents of the zip file
        run: unzip -l my-app.zip

    # Build trust between GitHub and AWS using OIDC connector
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ARN }}
          role-session-name: samplerolesession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Deployment Package to S3
        run: |
          aws s3 cp my-app.zip s3://ignite-jar-bucket/my-app.zip

  # CD Job
  deploy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
    # Build trust between GitHub and AWS using OIDC connector
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ARN }}
          role-session-name: samplerolesession
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name "ignite-app" \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name "ignite-DG" \
            --description "Deployment from GitHub Actions with S3" \
            --file-exists-behavior OVERWRITE \
            --s3-location bucket=ignite-jar-bucket,key=my-app.zip,bundleType=zip
